FROM ghcr.io/rocker-org/devcontainer/geospatial:4.2

## Install additional deps like this:
# RUN R -e 'remotes::install_github("rspatial/terra")'

## Or like this:
# RUN R -e 'remotes::install_deps()'

